version: '3'
services:
  # node:
  #   container_name: document_node
  #   command: npm run start
  #   environment:
  #     NPM_INSTALL: ENABLE
  #     TYPEORM_MIGRATION: ENABLE
  #   ports:
  #     - 3000:3000
  postgres:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="demo-api","demo-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - contract_api_data:/data/postgres
    ports:
      - 5432:5432
volumes:
  contract_api_data: {}
