BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Votes] (
    [id] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Votes_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [voteId] INT NOT NULL,
    CONSTRAINT [Votes_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[Pokemons] (
    [id] INT NOT NULL,
    [name] NVARCHAR(1000) NOT NULL,
    [spriteUrl] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Pokemons_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[Votes] ADD CONSTRAINT [Votes_voteId_fkey] FOREIGN KEY ([voteId]) REFERENCES [dbo].[Pokemons]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
