#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ "$NO_VERIFY" ] || [ "$NO_VERIFY_YOLO" ]; then exit 0; fi

case "$OSTYPE" in
  msys*) exec < /dev/console && node_modules/.bin/cz --hook || true ;;
  *) exec < /dev/tty && node_modules/.bin/cz --hook || true ;;
esac